package com.nexuswms.fulfillment.controller;

import com.nexuswms.fulfillment.dto.request.PickItemRequest;
import com.nexuswms.fulfillment.dto.response.PickListItemResponse;
import com.nexuswms.fulfillment.dto.response.PickListResponse;
import com.nexuswms.fulfillment.service.PickListService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse; 
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

/**
 * REST controller for pick list management operations.
 *
 * <p>Pick lists are generated by managers from fulfillment requests and
 * assigned to pickers. Pickers use this API to retrieve their assigned
 * lists and record item picks as they physically collect goods from shelves.</p>
 */
@RestController
@RequestMapping("/api/v${spring.mvc.apiversion.supported}/pick-lists")
@RequiredArgsConstructor
@Tag(name = "Pick Lists", description = "Pick list generation, retrieval, and item picking")
public class PickListController {

    private final PickListService pickListService;

    /**
     * Generates a pick list for a fulfillment request and assigns it to a picker.
     * Shelf locations and batch IDs are resolved automatically from available stock.
     * Transitions the fulfillment request from PENDING to IN_PROGRESS
     * and the order from VALIDATED to PICKING.
     *
     * @param fulfillmentRequestId UUID of the fulfillment request to generate a pick list for.
     * @param assignedTo           UUID of the picker to assign the pick list to.
     * @param principalUserId      UUID of the authenticated manager extracted from the JWT.
     * @return 201 Created with the generated pick list and its items.
     */
    @Operation(summary = "Generate a pick list from a fulfillment request")
    @ApiResponse(responseCode = "201", description = "Pick list generated successfully") 
    @PostMapping("/generate")
    @PreAuthorize("hasAnyRole('ADMIN', 'MANAGER')")
    public ResponseEntity<PickListResponse> generate(
            @RequestParam UUID fulfillmentRequestId,
            @RequestParam UUID assignedTo,
            @AuthenticationPrincipal String principalUserId
    ) {
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(pickListService.generate(
                        fulfillmentRequestId,
                        assignedTo,
                        UUID.fromString(principalUserId)));
    }

    /**
     * Returns all pick lists assigned to the currently authenticated picker.
     *
     * @param principalUserId UUID of the authenticated picker extracted from the JWT.
     * @return 200 OK with the list of pick lists assigned to the current worker.
     */
    @Operation(summary = "Get pick lists assigned to the current worker")
    @ApiResponse(responseCode = "200", description = "Pick lists retrieved successfully")
    @GetMapping("/my")
    @PreAuthorize("hasAnyRole('ADMIN', 'PICKER')")
    public ResponseEntity<List<PickListResponse>> getMyPickLists(
            @AuthenticationPrincipal String principalUserId
    ) {
        return ResponseEntity.ok(pickListService.getByWorker(UUID.fromString(principalUserId)));
    }

    /**
     * Returns a single pick list by its UUID including all items and their status.
     *
     * @param id UUID of the pick list to retrieve.
     * @return 200 OK with the pick list and its items.
     */
    @Operation(summary = "Get pick list by ID")
    @ApiResponse(responseCode = "200", description = "Pick list retrieved successfully") 
    @GetMapping("/{id}")
    @PreAuthorize("hasAnyRole('ADMIN', 'MANAGER', 'PICKER')")
    public ResponseEntity<PickListResponse> getById(@PathVariable UUID id) {
        return ResponseEntity.ok(pickListService.getById(id));
    }

    /**
     * Records the picking of a specific item on a pick list.
     * Called by the picker when they physically collect an item from its shelf location.
     * When all items on the pick list are picked, the list auto-transitions to COMPLETED.
     *
     * @param id              UUID of the pick list containing the item.
     * @param itemId          UUID of the specific pick list item being picked.
     * @param request         Payload containing the quantity picked.
     * @param principalUserId UUID of the authenticated picker extracted from the JWT.
     * @return 200 OK with the updated pick list item.
     */
    @Operation(summary = "Record an item pick on a pick list")
    @ApiResponse(responseCode = "200", description = "Item picked successfully") 
    @PostMapping("/{id}/items/{itemId}/pick")
    @PreAuthorize("hasAnyRole('ADMIN', 'PICKER')")
    public ResponseEntity<PickListItemResponse> pickItem(
            @PathVariable UUID id,
            @PathVariable UUID itemId,
            @Valid @RequestBody PickItemRequest request,
            @AuthenticationPrincipal String principalUserId
    ) {
        return ResponseEntity.ok(
                pickListService.pickItem(id, itemId, request, UUID.fromString(principalUserId)));
    }
}